# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.13
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: yenugulasharan8019@gmail.com
author_name: Sharan Kumar
cloud_provider: vercel
preset_name: production
project_name: Nftmarketplace

